# Generated by Django 4.2.3 on 2023-08-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0004_bookonline_textarean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookonline',
            old_name='textarean',
            new_name='textarea',
        ),
    ]
