# Generated by Django 4.2.3 on 2023-07-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Phone',
            new_name='phone',
        ),
    ]
