# Generated by Django 4.2.3 on 2023-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0002_rename_phone_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='non', max_length=50)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('phone', models.IntegerField(default='0', max_length=12)),
                ('city', models.TextField(default='null', max_length=50)),
                ('service_name', models.TextField(default='null', max_length=1000)),
            ],
        ),
    ]
