# Generated by Django 4.2.3 on 2023-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0003_bookonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookonline',
            name='textarean',
            field=models.TextField(default='null', max_length=500),
        ),
    ]
