# Generated by Django 4.2.3 on 2023-08-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0005_rename_textarean_bookonline_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookonline',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
