# Generated by Django 4.2.3 on 2023-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISWebSite', '0006_alter_bookonline_phone_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookonline',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
